[config]
schemaVersion = "0.0.1"


[package]
namespace = "Lotus_Ecarlate"
name = "Lotus_Ecarlate_Lethal_Company"
versionNumber = "0.2.1"
description = "Custom Thunderstore modpack for Lotus Écarlate's Lethal Company sessions. Nothing to see here, get to work employee!"
websiteUrl = "https://github.com/nbusseneau/lotus-ecarlate-lethal-company-modpack"
containsNsfwContent = false

[package.dependencies]
anormaltwig-LateCompany = "1.0.13"
BepInEx-BepInExPack = "5.4.2100"
BottomBois-More_Suits = "1.4.3"
EliteMasterEric-Coroner = "1.6.2"
notnotnotswipez-MoreCompany = "1.9.1"
RickArg-Helmet_Cameras = "2.1.5"
RugbugRedfern-Skinwalkers = "5.0.0"
Spacstic-More_Emotes = "1.3.3"
stefan750-LCUltrawide = "1.1.1"
Suskitech-AlwaysHearActiveWalkies = "1.4.5"
tinyhoot-ShipLoot = "1.1.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./config"
target = "./config"


[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", ]

[publish.categories]
lethal-company = [ "modpacks", ]
